### PR TITLE
Modify the RPM build spec for not modifying hv_compat.h

### PR DESCRIPTION
**Pull request by DivyaJyothiKasam**

### CODE REVIEW

**Comment by DivyaJyothiKasam** [comment]
[root@RHEL75 LISISO]# ./install.sh
Invoking release specific install file in directory RPMS75
Removing Hyper-V daemons
Removing Hyper-V Tools
Installing the Linux Integration Services for Microsoft Hyper-V...
Preparing...                          ########################################
Updating / installing...
kmod-microsoft-hyper-v-4.3.3.1-2019061########################################
microsoft-hyper-v-4.3.3.1-20190619    ########################################
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
microsoft-hyper-v-debuginfo-4.3.3.1-20########################################
 Linux Integration Services for Hyper-V has been installed. Please reboot your system.


[lisa@RHEL75 ~]$ modinfo hv_vmbus
filename:       /lib/modules/3.10.0-862.32.2.el7.x86_64/weak-updates/microsoft-hyper-v/hv_vmbus.ko
version:        4.3.3
license:        GPL
retpoline:      Y
rhelversion:    7.5
srcversion:     59E987DB2E59BED7DD3025F
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:
vermagic:       3.10.0-862.14.4.el7.x86_64 SMP mod_unload modversions
parm:           affinity_mode:vmbus channel cpu affinity mode: 0, 1 (int)

**Review by prashantmhetar — COMMENTED** [review]
Changes looks good.
Please modify commit message. It can be
"Modify the RPM build spec to avoid version change in hv_compat.h"

**Comment by DivyaJyothiKasam** [comment]
@prashantmhetar @iamshital @santoshx please review it.

**Comment by santoshx** [comment]
Looks good.

**Comment by DivyaJyothiKasam** [comment]
> Changes looks good.
> Please modify commit message. It can be
> "Modify the RPM build spec to avoid version change in hv_compat.h"

Changed the commit message.

**Review by prashantmhetar — APPROVED** [review]

**Pull request merged**
