### PR TITLE
Add Kernel 3.10.0-514.62.1.el7.x86_64 for RH73

### PR DESCRIPTION
**Pull request by DivyaJyothiKasam**
kernel 3.10.0-693.44.1.el7.x86_64 for RH74

### CODE REVIEW

**Comment by DivyaJyothiKasam** [comment]
For RH74:
[root@centos74x64 ~]# uname -a
Linux centos74x64 3.10.0-693.44.1.el7.x86_64 #1 SMP Tue Jan 22 16:32:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

For RH73:
[root@centos73x64 ~]# uname -a
Linux centos73x64 3.10.0-514.62.1.el7.x86_64 #1 SMP Thu Jan 31 12:34:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Review by prashantmhetar — COMMENTED** [review]
Please share install, uninstall and upgrade unit test logs for these new errata kernels

**Comment by DivyaJyothiKasam** [comment]
Performed unit testing by creating RPM.s on Build machine. Observed the RPM.s getting created in below paths 
LISISO/RHEL73/update18 and LISISO/RHEL74/update11 
LISISO/CentOS73/update18 and LISISO/CentOS7374/update11 
LISISO/Oracle73/update18 and LISISO/Oracle74/update11 

Once the code is merged and tar is ready. will perform the install, uninstall and upgrade testing for new Errata kernels

**Comment by DivyaJyothiKasam** [comment]
Install, uninstall and upgrade Logs for RHEL73(3.10.0-514.62.1.el7.x86_64)
]0;root@rhel73:~/LISISO[root@rhel73 LISISO]# ./install.sh 
Removing Hyper-V daemons
Removing Hyper-V Tools
Invoking release specific install file in directory RHEL73
Installing the Linux Integration Services for Microsoft Hyper-V...
Preparing...                                                           
Updating / installing...
   1:kmod-microsoft-hyper-v-4.2.8.2-20                                
   2:microsoft-hyper-v-4.2.8.2-2019022                                
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
   3:microsoft-hyper-v-debuginfo-4.2.8                                  
 Linux Integration Services for Hyper-V has been installed. Please reboot your system.

]0;root@rhel73:~[root@rhel73 ~]# modinfo hv_vmbus
filename:       /lib/modules/3.10.0-514.62.1.el7.x86_64/extra/microsoft-hyper-v/hv_vmbus.ko
version:        4.2.8.2
license:        GPL
retpoline:      Y
rhelversion:    7.3
srcversion:     804FA63F00182C971BEE100
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:        
vermagic:       3.10.0-514.62.1.el7.x86_64 SMP mod_unload modversions 
parm:           affinity_mode:vmbus channel cpu affinity mode: 0, 1 (int)

]0;root@rhel73:~/LISISO[root@rhel73 LISISO]# ./uninstall.sh 
Uninstalling the Linux Integration Services for Microsoft Hyper-V...
Removing Package..
Stopping KVP Daemon....
Stopping FCOPY Daemon....
Stopping VSS Daemon....
Create and install initramfs without Hyper-V drivers
Linux Integration Services for Hyper-V has been removed.  Please reboot your system.
Uninstalled Linux Integration Services for Microsoft Hyper-V...

]0;root@rhel73:~[root@rhel73 ~]# modinfo hv_vmbus
filename:       /lib/modules/3.10.0-514.62.1.el7.x86_64/kernel/drivers/hv/hv_vmbus.ko
license:        GPL
retpoline:      Y
rhelversion:    7.3
srcversion:     484246B4A3D5ED4657B200D
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:        
intree:         Y
vermagic:       3.10.0-514.62.1.el7.x86_64 SMP mod_unload modversions 
signer:         Red Hat Enterprise Linux kernel signing key
sig_key:        5F:E6:A4:99:C4:37:44:99:A9:4A:CA:83:E1:7E:2E:65:51:BC:18:C9
sig_hashalgo:   sha256

]0;root@rhel73:~/LISISO[root@rhel73 LISISO]# ./upgrade.sh 
Removing Hyper-V daemons
Removing Hyper-V Tools
Invoking release specific install file in directory RHEL73
Preparing...                                                            
Updating / installing...
   1:kmod-microsoft-hyper-v-4.2.8.2-20                                  
   2:microsoft-hyper-v-4.2.8.2-2019022                                
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
   3:microsoft-hyper-v-debuginfo-4.2.8                                 
Linux Integration Services for Hyper-V has been Upgraded. Please reboot your system

]0;root@rhel73:~[root@rhel73 ~]# modinfo hv_vmbus
filename:       /lib/modules/3.10.0-514.62.1.el7.x86_64/extra/microsoft-hyper-v/hv_vmbus.ko
version:        4.2.8.2
license:        GPL
retpoline:      Y
rhelversion:    7.3
srcversion:     804FA63F00182C971BEE100
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:        
vermagic:       3.10.0-514.62.1.el7.x86_64 SMP mod_unload modversions 
parm:           affinity_mode:vmbus channel cpu affinity mode: 0, 1 (int)

**Comment by DivyaJyothiKasam** [comment]
Install, uninstall and upgrade Logs for RHEL74(3.10.0-693.44.1.el7.x86_64)
]0;root@rhel74:~/LISISO[root@rhel74 LISISO]# ./install.sh 
Removing Hyper-V daemons
Removing Hyper-V Tools
Invoking release specific install file in directory RHEL74
Installing the Linux Integration Services for Microsoft Hyper-V...
Preparing...                                                            
Updating / installing...
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
   3:microsoft-hyper-v-debuginfo-4.2.8                                  
 Linux Integration Services for Hyper-V has been installed. Please reboot your system.
 
 ]0;root@rhel74:~[root@rhel74 ~]# modinfo hv_vmbus
filename:       /lib/modules/3.10.0-693.44.1.el7.x86_64/extra/microsoft-hyper-v/hv_vmbus.ko
version:        4.2.8.2
license:        GPL
retpoline:      Y
rhelversion:    7.4
srcversion:     804FA63F00182C971BEE100
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:        
vermagic:       3.10.0-693.44.1.el7.x86_64 SMP mod_unload modversions 
parm:           affinity_mode:vmbus channel cpu affinity mode: 0, 1 (int)

]0;root@rhel74:~/LISISO[root@rhel74 LISISO]# ./uinst[K[K[K[Kninstall.sh 
Uninstalling the Linux Integration Services for Microsoft Hyper-V...
Removing Package..
Stopping KVP Daemon....
Stopping FCOPY Daemon....
Stopping VSS Daemon....
Create and install initramfs without Hyper-V drivers
Linux Integration Services for Hyper-V has been removed.  Please reboot your system.
Uninstalled Linux Integration Services for Microsoft Hyper-V...


]0;root@rhel74:~[root@rhel74 ~]# modinfo hv_vmbus
filename:       /lib/modules/3.10.0-693.44.1.el7.x86_64/kernel/drivers/hv/hv_vmbus.ko.xz
license:        GPL
retpoline:      Y
rhelversion:    7.4
srcversion:     86197E4D8C8D98D2C91168D
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:        
intree:         Y
vermagic:       3.10.0-693.44.1.el7.x86_64 SMP mod_unload modversions 
signer:         Red Hat Enterprise Linux kernel signing key
sig_key:        5C:50:89:7B:5E:6B:8C:9F:BC:94:07:FC:1F:7A:B0:81:9B:90:9A:CF
sig_hashalgo:   sha256


]0;root@rhel74:~/LISISO[root@rhel74 LISISO]# ./upgrade.sh 
Removing Hyper-V daemons
Removing Hyper-V Tools
Invoking release specific install file in directory RHEL74
Preparing...                                                       
Updating / installing...
   1:kmod-microsoft-hyper-v-4.2.8.2-20                                
   2:microsoft-hyper-v-4.2.8.2-2019022                               2%)#                                 (  
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
   3:microsoft-hyper-v-debuginfo-4.2.8                            
Linux Integration Services for Hyper-V has been Upgraded. Please reboot your system


]0;root@rhel74:~[root@rhel74 ~]# modinfo hv_vmbuys[K[Ks
filename:       /lib/modules/3.10.0-693.44.1.el7.x86_64/extra/microsoft-hyper-v/hv_vmbus.ko
version:        4.2.8.2
license:        GPL
retpoline:      Y
rhelversion:    7.4
srcversion:     804FA63F00182C971BEE100
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:        
vermagic:       3.10.0-693.44.1.el7.x86_64 SMP mod_unload modversions 
parm:           affinity_mode:vmbus channel cpu affinity mode: 0, 1 (int)

**Pull request merged**
