### PR TITLE
rh7: Install mlx ofed 4.5 kernel modules for rhel73

### PR DESCRIPTION
**Pull request by santoshx**
Build machines needs at least 1GB of RAM otherwise
mlx ofed build fails.

### CODE REVIEW

**Comment by santoshx** [comment]
@mboitei @prashantmhetar Please review this.

**Comment by mboitei** [comment]
Please upload the logs for the test and let us know what is the build size difference between the old build and new build.  
Adding @prashantmhetar here

**Comment by santoshx** [comment]
4.2.8 as is: 726MB
4.2.8 with mlx ofed 4.5 is: 1.2GB
https://linuxpipeline.westus2.cloudapp.azure.com/blue/organizations/jenkins/pipeline-lis-rpm-build/detail/pipeline-lis-rpm-build/178/pipeline

**Comment by santoshx** [comment]
@mboitei @prashantmhetar Please merge this.

**Pull request merged**
