### PR TITLE
Add Kernel 3.10.0-862.29.1.el7.x86_64 for RH75

### PR DESCRIPTION
**Pull request by DivyaJyothiKasam**

### CODE REVIEW

**Comment by DivyaJyothiKasam** [comment]
Kernel version:
[lisa@centos75 ~]$ uname -r
3.10.0-862.29.1.el7.x86_64
[lisa@centos75 ~]$ uname -a
Linux centos75 3.10.0-862.29.1.el7.x86_64 #1 SMP Tue Feb 5 09:24:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Review by prashantmhetar — COMMENTED** [review]
generate the new rpm with this change and verify with install, upgrade and uninstall for new kernel.

**Comment by DivyaJyothiKasam** [comment]
> generate the new rpm with this change and verify with install, upgrade and uninstall for new kernel.

Generated a new RPM build with support for New Errata Kernel.
https://linuxpipelineshare.blob.core.windows.net/lis-rpm-builds/lis-builds/lis-rpm-4.3.0.Errata-2019-03-15.09.07.tar.gz

Done unit testing for Install, Uninstall and Upgrade scenarios for Centos 75, RHEL 75 and Oracle 75 with new Errata Kernel.

**Comment by DivyaJyothiKasam** [comment]
Logs:
######################################INSTALL_SCENARIO########################################
[root@centos75 LISISO]# ./install.sh 
Removing Hyper-V daemons
Removing the hyperv-daemons package
Removing the hypervfcopyd package
Removing the hypervkvpd package
Removing the hypervvssd package
Removing the hyperv-daemons-license package
Removing Hyper-V Tools
Removing the hyperv-tools package
Invoking release specific install file in directory RPMS75
Installing the Linux Integration Services for Microsoft Hyper-V...
Preparing...                          ########################################
Updating / installing...
kmod-microsoft-hyper-v-4.3.0.Errata-20########################################
microsoft-hyper-v-4.3.0.Errata-2019031########################################
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
microsoft-hyper-v-debuginfo-4.3.0.Erra########################################
 Linux Integration Services for Hyper-V has been installed. Please reboot your system.
]0;root@centos75:~/LISISO [root@centos75 LISISO]# reboot
login as: root
root@10.128.72.229's password: 
Last login: Fri Mar 15 03:32:39 2019 from lis-f2325.redmond.corp.microsoft.com]0;root@centos75:~ [?1034h[root@centos75 ~]# 
]0;root@centos75:~ [root@centos75 ~]# 
]0;root@centos75:~ [root@centos75 ~]# modinfo hv_vmbus
filename:       /lib/modules/3.10.0-862.29.1.el7.x86_64/extra/microsoft-hyper-v/hv_vmbus.ko
version:        4.3.0.Errata
license:        GPL
retpoline:      Y
rhelversion:    7.5
srcversion:     CE2964B6A2652C90F0333C1
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:        
vermagic:       3.10.0-862.29.1.el7.x86_64 SMP mod_unload modversions 
parm:           affinity_mode:vmbus channel cpu affinity mode: 0, 1 (int)

######################################UNINSTALL_SCENARIO########################################
[root@centos75 LISISO]# ./uninstall.sh 
Uninstalling the Linux Integration Services for Microsoft Hyper-V...
Removing Package..
Stopping KVP Daemon....
Stopping FCOPY Daemon....
Stopping VSS Daemon....
Create and install initramfs without Hyper-V drivers
Linux Integration Services for Hyper-V has been removed.  Please reboot your system.
Uninstalled Linux Integration Services for Microsoft Hyper-V...
]0;root@centos75:~/LISISO [root@centos75 LISISO]# reboot
login as: root
root@10.128.72.229's password: 
Last login: Fri Mar 15 03:38:01 2019 from lis-f2325.redmond.corp.microsoft.com]0;root@centos75:~ [?1034h[root@centos75 ~]# 
]0;root@centos75:~ [root@centos75 ~]# modinfo hv_vmbus
filename:       /lib/modules/3.10.0-862.29.1.el7.x86_64/kernel/drivers/hv/hv_vmbus.ko.xz
license:        GPL
retpoline:      Y
rhelversion:    7.5
srcversion:     FDEC375DD4661BC80D39F62
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:        
intree:         Y
vermagic:       3.10.0-862.29.1.el7.x86_64 SMP mod_unload modversions 
signer:         Red Hat Enterprise Linux kernel signing key
sig_key:        5E:79:5F:9D:BA:51:1F:47:07:EA:C0:08:11:8A:BC:07:BB:E0:65:BC
sig_hashalgo:   sha256

######################################UPGRADE_SCENARIO########################################
[root@centos75 LISISO]# ./upgrade.sh 
Removing Hyper-V daemons
Removing Hyper-V Tools
Invoking release specific install file in directory RPMS75
Preparing...                          ########################################
Updating / installing...
kmod-microsoft-hyper-v-4.3.0.Errata-20########################################
microsoft-hyper-v-4.3.0.Errata-2019031########################################
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
microsoft-hyper-v-debuginfo-4.3.0.Erra########################################
Linux Integration Services for Hyper-V has been Upgraded. Please reboot your system
]0;root@centos75:~/LISISO [root@centos75 LISISO]# reboot
login as: root
root@10.128.72.229's password: 
Last login: Fri Mar 15 03:42:30 2019 from lis-f2325.redmond.corp.microsoft.com]0;root@centos75:~ [?1034h[root@centos75 ~]# 
]0;root@centos75:~ [root@centos75 ~]# modinfo hv_vmbus
filename:       /lib/modules/3.10.0-862.29.1.el7.x86_64/extra/microsoft-hyper-v/hv_vmbus.ko
version:        4.3.0.Errata
license:        GPL
retpoline:      Y
rhelversion:    7.5
srcversion:     CE2964B6A2652C90F0333C1
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:        
vermagic:       3.10.0-862.29.1.el7.x86_64 SMP mod_unload modversions 
parm:           affinity_mode:vmbus channel cpu affinity mode: 0, 1 (int)

**Review by prashantmhetar — APPROVED** [review]

**Pull request merged**
