### PR TITLE
Add Kernel 3.10.0-957.10.1.el7.x86_64 for RH76

### PR DESCRIPTION
**Pull request by DivyaJyothiKasam**

### CODE REVIEW

**Comment by DivyaJyothiKasam** [comment]
[root@localhost ~]# [root@localhost ~]# uname -r 
3.10.0-957.10.1.el7.x86_64
[root@localhost ~]# uname -a 
Linux localhost.localdomain 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Review by prashantmhetar — COMMENTED** [review]
Code changes looks good. 
Please add the install/uninstall/upgrade for this errata kernel

**Comment by prashantmhetar** [comment]
Merging this PR , once RPM is ready verify for this errata kernel

**Comment by DivyaJyothiKasam** [comment]
###################INSTALL_SCENARIO################################
[root@rhel76 LISISO]# ./install.sh
Removing Hyper-V daemons
Removing the hyperv-daemons package
Removing the hypervfcopyd package
Removing the hypervkvpd package
Removing the hypervvssd package
Removing the hyperv-daemons-license package
Removing Hyper-V Tools
Removing the hyperv-tools package
Invoking release specific install file in directory RPMS76
Installing the Linux Integration Services for Microsoft Hyper-V...
Preparing...                          ########################################
Updating / installing...
kmod-microsoft-hyper-v-4.3.0-20190327 ########################################
microsoft-hyper-v-4.3.0-20190327      ########################################
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
microsoft-hyper-v-debuginfo-4.3.0-2019########################################
 Linux Integration Services for Hyper-V has been installed. Please reboot your system.
[root@rhel76 LISISO]# reboot

[root@rhel76 ~]# modinfo hv_vmbus
filename:       /lib/modules/3.10.0-957.10.1.el7.x86_64/extra/microsoft-hyper-v/hv_vmbus.ko
version:        4.3.0
license:        GPL
retpoline:      Y
rhelversion:    7.6
srcversion:     CE2964B6A2652C90F0333C1
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:
vermagic:       3.10.0-957.10.1.el7.x86_64 SMP mod_unload modversions
parm:           affinity_mode:vmbus channel cpu affinity mode: 0, 1 (int)


###################UNINSTALL_SCENARIO################################
[root@rhel76 ~]#
[root@rhel76 ~]# cd LISISO/
[root@rhel76 LISISO]# ./uninstall.sh
Uninstalling the Linux Integration Services for Microsoft Hyper-V...
Removing Package..
Stopping KVP Daemon....
Stopping FCOPY Daemon....
Stopping VSS Daemon....
Create and install initramfs without Hyper-V drivers
Linux Integration Services for Hyper-V has been removed.
Uninstalled Linux Integration Services for Microsoft Hyper-V. Please reboot your system.

[root@rhel76 ~]# modinfo hv_vmbus
filename:       /lib/modules/3.10.0-957.10.1.el7.x86_64/kernel/drivers/hv/hv_vmbus.ko.xz
license:        GPL
retpoline:      Y
rhelversion:    7.6
srcversion:     2899208793654F2260111F6
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:
intree:         Y
vermagic:       3.10.0-957.10.1.el7.x86_64 SMP mod_unload modversions
signer:         Red Hat Enterprise Linux kernel signing key
sig_key:        A5:70:18:DF:B6:C9:D6:1F:CF:CE:0A:3D:02:8B:B3:69:BD:76:CA:ED
sig_hashalgo:   sha256

###################UPGRADE_SCENARIO################################
[root@rhel76 LISISO]# ./upgrade.sh
Removing Hyper-V daemons
Removing Hyper-V Tools
Invoking release specific install file in directory RPMS75
Preparing... ########################################
Updating / installing...
kmod-microsoft-hyper-v-4.3.0.Errata-20########################################
microsoft-hyper-v-4.3.0.Errata-2019031########################################
Saving old initramfs
Installing new initramfs
Starting KVP Daemon....
Starting VSS Daemon....
Starting FCOPY Daemon....
microsoft-hyper-v-debuginfo-4.3.0.Erra########################################
Linux Integration Services for Hyper-V has been Upgraded. Please reboot your system


[root@rhel76 ~]# modinfo hv_vmbus
filename:       /lib/modules/3.10.0-957.10.1.el7.x86_64/extra/microsoft-hyper-v/hv_vmbus.ko
version:        4.3.0
license:        GPL
retpoline:      Y
rhelversion:    7.6
srcversion:     CE2964B6A2652C90F0333C1
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:
vermagic:       3.10.0-957.10.1.el7.x86_64 SMP mod_unload modversions
parm:           affinity_mode:vmbus channel cpu affinity mode: 0, 1 (int)

**Pull request merged**
