### PR TITLE
Enhancement in uninstall script in LIS RPM

### PR DESCRIPTION
**Pull request by DivyaJyothiKasam**

### CODE REVIEW

**Comment by DivyaJyothiKasam** [comment]
Logs for uninstall scenario:
[root@rhel76 LISISO]# ./uninstall.sh
Uninstalling the Linux Integration Services for Microsoft Hyper-V...
Removing Package..
Stopping KVP Daemon....
Stopping FCOPY Daemon....
Stopping VSS Daemon....
Create and install initramfs without Hyper-V drivers
Linux Integration Services for Hyper-V has been removed.
Uninstalled Linux Integration Services for Microsoft Hyper-V. Please reboot your system.

**Comment by DivyaJyothiKasam** [comment]
Logs for 6.5 distro:
Logs for 6.x series distro.
##############Install#######################
[root@localhost LISISO]# ./install.sh 
Removing Hyper-V daemons
Removing Hyper-V Tools
Invoking release specific install file in directory RPMS65
Installing the Linux Integration Services for Microsoft Hyper-V...
Preparing...                                                            (100%)#    
 1:kmod-microsoft-hyper-v  
Preparing...  
 1:microsoft-hyper-v-debug 
 2:microsoft-hyper-v    
Saving old initramfs
Installing new initramfs
Adding KVP Daemon to Chkconfig....
Starting KVP Daemon....
Adding VSS Daemon to Chkconfig....
Starting VSS Daemon....
Adding FCOPY Daemon to Chkconfig....
Starting FCOPY Daemon....
 Linux Integration Services for Hyper-V has been installed. Please reboot your system.
]0;root@localhost:~/LISISO[root@localhost LISISO]# reboot

[?1034h[root@localhost ~]# modinfo hv_vmbus
filename:       /lib/modules/2.6.32-431.el6.x86_64/extra/hv_vmbus.ko
version:        master
license:        GPL
srcversion:     8B8545E8070D9C9E95A7EE0
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:        
vermagic:       2.6.32-431.el6.x86_64 SMP mod_unload modversions 
[root@localhost ~]# 
[root@localhost ~]# 
[root@localhost ~]#ls
[0m[01;34mdivya[0m  [01;34mLISISO[0m  [01;31mlis-rpm-4.3.1-2019-03-20.06.31.tar.gz[0m
[m[root@localhost ~]# cd LISISO/
##############Uninstall#######################
]0;root@localhost:~/LISISO[root@localhost LISISO]# ./uninstall.sh 
Uninstalling the Linux Integration Services for Microsoft Hyper-V...
Removing Package..
Stopping KVP Daemon....
Deleting KVP Daemon from Chkconfig....
Stopping VSS Daemon....
Deleting VSS Daemon from Chkconfig....
Stopping FCOPY Daemon....
Deleting FCOPY Daemon from Chkconfig....
Create and install initramfs without Hyper-V drivers
Linux Integration Services for Hyper-V has been removed.
Uninstalled Linux Integration Services for Microsoft Hyper-V. Please reboot your system.

**Comment by DivyaJyothiKasam** [comment]
Logs for Centos511:
##############Install#######################
[root@localhost LISISO]# ./install.sh 
Removing Hyper-V daemons
Removing the hypervkvpd package
Removing Hyper-V Tools
Invoking release specific install file in directory RPMS511
Installing the Linux Integration Services for Microsoft Hyper-V...
Preparing...                                                            (100%)#                                           (100%)##                                          (
   1:kmod-microsoft-hyper-v                                             (  1%)#                                           (  4%)##                                          (  6%)###                                         (  
Preparing...                                                            ( 50%)#                                           ( (100%)########################################### [100%]
   1:microsoft-hyper-v-debug                                            ( (100%)########################################### [ 50%]
   2:microsoft-hyper-v                                                  (  2%)#                                           (  (100%)########################################### [100%]
Saving old initrd
Installing new initrd
	Done.
Adding KVP Daemon to Chkconfig....
Starting KVP Daemon....
Adding VSS Daemon to Chkconfig....
Starting VSS Daemon....
Adding FCOPY Daemon to Chkconfig....
Starting FCOPY Daemon....
 Linux Integration Services for Hyper-V has been installed. Please reboot your system
]0;root@localhost:~/LISISO[root@localhost LISISO]# reboot

##############UnInstall#######################
[m]0;root@localhost:~/LISISO[root@localhost LISISO]# ./uninstall.sh 
Uninstalling the Linux Integration Services for Microsoft Hyper-V...
Removing Package..
Stopping KVP Daemon....
Deleting KVP Daemon from Chkconfig....
Stopping VSS Daemon....
Deleting VSS Daemon from Chkconfig....
Stopping FCOPY Daemon....
Deleting FCOPY Daemon from Chkconfig....
Create and install initrd without Hyper-V drivers
Linux Integration Services for Hyper-V has been removed.Please remove hda=noprobe hdb=noprobe from grub file
Uninstalled Linux Integration Services for Microsoft Hyper-V. Please reboot your system.

**Comment by johnsongeorge-w** [comment]
Looks good.

**Review by iamshital — APPROVED** [review]

**Pull request merged**
